import { useCallback,useEffect,useRef,useState } from 'react';
import { ActivityIndicator,FlatList,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import { supabase } from '../../lib/supabase';
import { useSession } from '../../lib/session';
import { colors } from '../../lib/theme';
import type { Message } from '../../lib/types';

const uuid=()=>('xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx').replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3)|8;return v.toString(16)});
export default function Chat(){
 const {id,name}=useLocalSearchParams<{id:string;name?:string}>();const {user}=useSession();const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState('');const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [typing,setTyping]=useState(false);const list=useRef<FlatList>(null);const typingTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const load=useCallback(async()=>{if(!id)return;const {data}=await supabase.from('messages').select('*, sender:profiles(*)').eq('conversation_id',id).is('deleted_at',null).order('created_at',{ascending:true}).limit(100);setMessages((data??[]) as Message[]);setLoading(false)},[id]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!id||!user)return;const channel=supabase.channel(`chat:${id}`,{config:{broadcast:{self:false}}}).on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},payload=>{if(payload.eventType==='INSERT')setMessages(p=>p.some(m=>m.id===payload.new.id||m.client_id===payload.new.client_id)?p:[...p,payload.new as Message]);else if(payload.eventType==='UPDATE')setMessages(p=>p.map(m=>m.id===payload.new.id?payload.new as Message:m))}).on('broadcast',{event:'typing'},({payload})=>{if(payload.userId!==user.id){setTyping(!!payload.typing);if(payload.typing)setTimeout(()=>setTyping(false),2200)}}).subscribe();return()=>{supabase.removeChannel(channel)}},[id,user]);
 useEffect(()=>{if(!id||!user)return;const last=messages.filter(m=>m.sender_id!==user.id).at(-1);if(last)supabase.from('message_receipts').upsert({message_id:last.id,user_id:user.id,read_at:new Date().toISOString(),delivered_at:new Date().toISOString()},{onConflict:'message_id,user_id'}).then(()=>{})},[messages,id,user]);
 function onChange(v:string){setText(v);if(!id||!user)return;const channel=supabase.channel(`chat:${id}`);channel.send({type:'broadcast',event:'typing',payload:{userId:user.id,typing:!!v.trim()}}).then(()=>{});if(typingTimer.current)clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>channel.send({type:'broadcast',event:'typing',payload:{userId:user.id,typing:false}}).then(()=>{}),1200)}
 async function send(){const body=text.trim();if(!body||!user||!id||sending)return;setText('');setSending(true);const clientId=uuid();const optimistic:Message={id:`local-${clientId}`,client_id:clientId,conversation_id:id,sender_id:user.id,body,message_type:'text',status:'sent',created_at:new Date().toISOString(),edited_at:null,deleted_at:null};setMessages(p=>[...p,optimistic]);const {data,error}=await supabase.from('messages').insert({client_id:clientId,conversation_id:id,sender_id:user.id,body,message_type:'text'}).select('*, sender:profiles(*)').single();setSending(false);if(error){setMessages(p=>p.map(m=>m.id===optimistic.id?{...m,status:'failed'}:m));return}setMessages(p=>p.map(m=>m.client_id===clientId?data as Message:m));setTimeout(()=>list.current?.scrollToEnd({animated:true}),50)}
 return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()} hitSlop={12}><Text style={s.back}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>CONVERSATION</Text><Text style={s.name}>{name??'Conversation'}</Text><Text style={s.status}>{typing?'typing…':'realtime channel'}</Text></View><Text style={s.dot}>●</Text></View>{loading?<ActivityIndicator color={colors.paper} style={{marginTop:40}}/>:<FlatList ref={list} data={messages} keyExtractor={m=>m.id} contentContainerStyle={s.messages} onContentSizeChange={()=>list.current?.scrollToEnd({animated:false})} renderItem={({item})=>{const mine=item.sender_id===user?.id;return <View style={[s.messageWrap,mine?s.right:s.left]}><View style={[s.bubble,mine?s.mine:s.theirs]}><Text style={[s.body,mine?s.mineBody:s.theirBody]}>{item.body}</Text><View style={s.metaRow}><Text style={[s.time,mine&&s.mineTime]}>{new Date(item.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text>{mine&&<Text style={s.check}>{item.status==='failed'?'!':item.status==='read'?'✓✓':'✓'}</Text>}</View></View></View>}}/>}<View style={s.composer}><Pressable style={s.attach}><Text style={s.attachText}>＋</Text></Pressable><TextInput value={text} onChangeText={onChange} multiline placeholder="Write a message" placeholderTextColor={colors.muted} style={s.input}/><Pressable onPress={send} disabled={sending||!text.trim()} style={[s.send,(!text.trim()||sending)&&s.disabled]}><Text style={s.sendText}>↑</Text></Pressable></View></KeyboardAvoidingView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},header:{height:104,paddingTop:48,paddingHorizontal:16,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,gap:10},back:{color:colors.paper,fontSize:38,fontWeight:'300'},eyebrow:{color:colors.muted,fontSize:9,fontWeight:'800',letterSpacing:1.5},name:{color:colors.paper,fontWeight:'700',fontSize:18,marginTop:2},status:{color:colors.muted,fontSize:11,marginTop:3},dot:{fontSize:9,color:colors.success},messages:{paddingHorizontal:14,paddingTop:14,paddingBottom:24},messageWrap:{maxWidth:'82%',marginVertical:3},right:{alignSelf:'flex-end'},left:{alignSelf:'flex-start'},bubble:{paddingHorizontal:13,paddingTop:9,paddingBottom:7,borderRadius:16},mine:{backgroundColor:colors.paper,borderBottomRightRadius:4},theirs:{backgroundColor:colors.panel2,borderWidth:1,borderColor:colors.line,borderBottomLeftRadius:4},body:{fontSize:15,lineHeight:20},mineBody:{color:colors.ink},theirBody:{color:colors.paper},metaRow:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:4,marginTop:4},time:{fontSize:9,color:colors.muted},mineTime:{color:'#77736B'},check:{fontSize:10,color:'#77736B'},composer:{minHeight:70,padding:10,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.line,flexDirection:'row',alignItems:'flex-end',gap:7,backgroundColor:colors.ink},attach:{width:42,height:46,alignItems:'center',justifyContent:'center'},attachText:{color:colors.paperMuted,fontSize:25,fontWeight:'300'},input:{flex:1,maxHeight:110,minHeight:46,borderRadius:16,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:14,paddingVertical:11,fontSize:15},send:{width:46,height:46,borderRadius:23,backgroundColor:colors.paper,alignItems:'center',justifyContent:'center'},disabled:{opacity:.3},sendText:{fontSize:22,color:colors.ink,fontWeight:'800'}});
