import { useCallback,useEffect,useRef,useState } from 'react';
import { ActivityIndicator,Alert,FlatList,KeyboardAvoidingView,Platform,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { router,useLocalSearchParams } from 'expo-router';
import * as ImagePicker from 'expo-image-picker';
import { supabase } from '../../lib/supabase';
import { useSession } from '../../lib/session';
import { colors } from '../../lib/theme';
import { enqueueMessage,flushQueue } from '../../lib/offlineQueue';
import type { Message } from '../../lib/types';
const uuid=()=>('xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx').replace(/[xy]/g,c=>{const r=Math.random()*16|0,v=c==='x'?r:(r&3)|8;return v.toString(16)});
export default function Chat(){
 const {id,name}=useLocalSearchParams<{id:string;name?:string}>();const {user}=useSession();const [messages,setMessages]=useState<Message[]>([]);const [text,setText]=useState('');const [loading,setLoading]=useState(true);const [sending,setSending]=useState(false);const [typing,setTyping]=useState(false);const [reply,setReply]=useState<Message|null>(null);const list=useRef<FlatList>(null);const channel=useRef<any>(null);const typingTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const load=useCallback(async()=>{if(!id)return;const {data}=await supabase.from('messages').select('*, sender:profiles(*)').eq('conversation_id',id).is('deleted_at',null).order('created_at',{ascending:true}).limit(100);setMessages((data??[]) as Message[]);setLoading(false);if(user)await supabase.rpc('mark_conversation_read',{p_conversation_id:id});void flushQueue()},[id,user]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!id||!user)return;const ch=supabase.channel(`chat:${id}`,{config:{broadcast:{self:false},presence:{key:user.id}}});channel.current=ch;ch.on('postgres_changes',{event:'*',schema:'public',table:'messages',filter:`conversation_id=eq.${id}`},payload=>{if(payload.eventType==='INSERT')setMessages(p=>p.some(m=>m.id===payload.new.id||m.client_id===payload.new.client_id)?p:[...p,payload.new as Message]);else if(payload.eventType==='UPDATE')setMessages(p=>p.map(m=>m.id===payload.new.id?payload.new as Message:m));else if(payload.eventType==='DELETE')setMessages(p=>p.filter(m=>m.id!==payload.old.id))}).on('broadcast',{event:'typing'},({payload})=>{if(payload.userId!==user.id){setTyping(!!payload.typing);if(payload.typing)setTimeout(()=>setTyping(false),2200)}}).on('presence',{event:'sync'},()=>{}).subscribe(async status=>{if(status==='SUBSCRIBED')await ch.track({online_at:new Date().toISOString()})});return()=>{if(typingTimer.current)clearTimeout(typingTimer.current);supabase.removeChannel(ch);channel.current=null}},[id,user]);
 useEffect(()=>{if(!id||!user)return;const last=messages.filter(m=>m.sender_id!==user.id).at(-1);if(last)supabase.from('message_receipts').upsert({message_id:last.id,user_id:user.id,read_at:new Date().toISOString(),delivered_at:new Date().toISOString()},{onConflict:'message_id,user_id'}).then(()=>{})},[messages,id,user]);
 function onChange(v:string){setText(v);channel.current?.send({type:'broadcast',event:'typing',payload:{userId:user?.id,typing:!!v.trim()}});if(typingTimer.current)clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>channel.current?.send({type:'broadcast',event:'typing',payload:{userId:user?.id,typing:false}}),1200)}
 async function send(body=text.trim(),attachment?:{uri:string,mime:string,name:string}){if(!body&&!attachment||!user||!id||sending)return;setText('');setSending(true);const clientId=uuid();const optimistic:any={id:`local-${clientId}`,client_id:clientId,conversation_id:id,sender_id:user.id,body:body||null,message_type:attachment?.mime.startsWith('image/')?'image':'text',status:'sent',created_at:new Date().toISOString(),edited_at:null,deleted_at:null};setMessages(p=>[...p,optimistic]);const {data,error}=await supabase.from('messages').insert({client_id:clientId,conversation_id:id,sender_id:user.id,body:body||null,message_type:optimistic.message_type,reply_to_id:reply?.id||null}).select('*, sender:profiles(*)').single();if(error){await enqueueMessage({id:optimistic.id,conversationId:id,senderId:user.id,body:body||'',clientId,createdAt:optimistic.created_at});setSending(false);setMessages(p=>p.map(m=>m.id===optimistic.id?{...m,status:'failed'}:m));setTimeout(()=>flushQueue(),500);return}if(attachment){try{const blob=await (await fetch(attachment.uri)).blob();const path=`${user.id}/${id}/${data.id}-${attachment.name}`;const up=await supabase.storage.from('chat-media').upload(path,blob,{contentType:attachment.mime,upsert:false});if(up.error)throw up.error;await supabase.from('attachments').insert({message_id:data.id,storage_path:path,mime_type:attachment.mime,file_name:attachment.name,file_size:blob.size});}catch(e:any){Alert.alert('Attachment upload failed',e.message||'Could not upload media.')}}setReply(null);setSending(false);setMessages(p=>p.map(m=>m.client_id===clientId?data as Message:m));setTimeout(()=>list.current?.scrollToEnd({animated:true}),50)}
 async function pickImage(){const perm=await ImagePicker.requestMediaLibraryPermissionsAsync();if(!perm.granted)return;const r=await ImagePicker.launchImageLibraryAsync({mediaTypes:['images'],quality:.82});if(!r.canceled&&r.assets[0]){const a=r.assets[0];await send('',{uri:a.uri,mime:a.mimeType||'image/jpeg',name:a.fileName||`image-${Date.now()}.jpg`})}}
 async function reactTo(message:Message){if(!user||message.id.startsWith('local-'))return;const {error}=await supabase.from('message_reactions').insert({message_id:message.id,user_id:user.id,reaction:'❤️'});if(error&&error.code!=='23505')Alert.alert('Reaction failed',error.message)}
 async function deleteMessage(message:Message){if(message.sender_id!==user?.id||message.id.startsWith('local-'))return;await supabase.from('messages').update({deleted_at:new Date().toISOString(),body:null}).eq('id',message.id)}
 return <KeyboardAvoidingView style={s.root} behavior={Platform.OS==='ios'?'padding':undefined}><View style={s.header}><Pressable onPress={()=>router.back()} hitSlop={12}><Text style={s.back}>‹</Text></Pressable><View style={{flex:1}}><Text style={s.eyebrow}>CONVERSATION</Text><Text style={s.name}>{name??'Conversation'}</Text><Text style={s.status}>{typing?'typing…':'secure realtime chat'}</Text></View><Text style={s.dot}>●</Text></View>{loading?<ActivityIndicator color={colors.paper} style={{marginTop:40}}/>:<FlatList ref={list} data={messages} keyExtractor={m=>m.id} contentContainerStyle={s.messages} onContentSizeChange={()=>list.current?.scrollToEnd({animated:false})} renderItem={({item})=>{const mine=item.sender_id===user?.id;return <Pressable onLongPress={()=>Alert.alert('Message',undefined,[{text:'Reply',onPress:()=>setReply(item)},{text:'React ❤️',onPress:()=>reactTo(item)},{text:'Delete',style:'destructive',onPress:()=>deleteMessage(item)},{text:'Cancel',style:'cancel'}])} style={[s.messageWrap,mine?s.right:s.left]}><View style={[s.bubble,mine?s.mine:s.theirs]}>{(item as any).reply_to_id&&<Text style={s.replyRef}>REPLY</Text>}<Text style={[s.body,mine?s.mineBody:s.theirBody]}>{item.body||'Media attachment'}</Text><View style={s.metaRow}><Text style={[s.time,mine&&s.mineTime]}>{new Date(item.created_at).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</Text>{mine&&<Text style={s.check}>{item.status==='failed'?'!':item.status==='read'?'✓✓':'✓'}</Text>}</View></View></Pressable>}}/>}<View style={s.composer}>{reply&&<View style={s.replyBar}><Text style={s.replyText}>Replying to message</Text><Pressable onPress={()=>setReply(null)}><Text style={s.close}>×</Text></Pressable></View>}<View style={s.composerRow}><Pressable style={s.attach} onPress={pickImage}><Text style={s.attachText}>＋</Text></Pressable><TextInput value={text} onChangeText={onChange} multiline placeholder="Write a message" placeholderTextColor={colors.muted} style={s.input}/><Pressable onPress={()=>send()} disabled={sending||!text.trim()} style={[s.send,(!text.trim()||sending)&&s.disabled]}><Text style={s.sendText}>↑</Text></Pressable></View></View></KeyboardAvoidingView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},header:{height:104,paddingTop:48,paddingHorizontal:16,flexDirection:'row',alignItems:'center',borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,gap:10},back:{color:colors.paper,fontSize:38,fontWeight:'300'},eyebrow:{color:colors.muted,fontSize:9,fontWeight:'800',letterSpacing:1.5},name:{color:colors.paper,fontWeight:'700',fontSize:18,marginTop:2},status:{color:colors.muted,fontSize:11,marginTop:3},dot:{fontSize:9,color:colors.success},messages:{paddingHorizontal:14,paddingTop:14,paddingBottom:24},messageWrap:{maxWidth:'82%',marginVertical:3},right:{alignSelf:'flex-end'},left:{alignSelf:'flex-start'},bubble:{paddingHorizontal:13,paddingTop:9,paddingBottom:7,borderRadius:16},mine:{backgroundColor:colors.paper,borderBottomRightRadius:4},theirs:{backgroundColor:colors.panel2,borderWidth:1,borderColor:colors.line,borderBottomLeftRadius:4},body:{fontSize:15,lineHeight:20},mineBody:{color:colors.ink},theirBody:{color:colors.paper},replyRef:{fontSize:9,color:colors.muted,letterSpacing:1,marginBottom:4},metaRow:{flexDirection:'row',justifyContent:'flex-end',alignItems:'center',gap:4,marginTop:4},time:{fontSize:9,color:colors.muted},mineTime:{color:'#77736B'},check:{fontSize:10,color:'#77736B'},composer:{padding:10,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.line,backgroundColor:colors.ink},composerRow:{minHeight:50,flexDirection:'row',alignItems:'flex-end',gap:7},replyBar:{height:28,flexDirection:'row',alignItems:'center',justifyContent:'space-between',paddingHorizontal:8},replyText:{color:colors.muted,fontSize:11},close:{color:colors.paper,fontSize:20},attach:{width:42,height:46,alignItems:'center',justifyContent:'center'},attachText:{color:colors.paperMuted,fontSize:25,fontWeight:'300'},input:{flex:1,maxHeight:110,minHeight:46,borderRadius:16,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:14,paddingVertical:11,fontSize:15},send:{width:46,height:46,borderRadius:23,backgroundColor:colors.paper,alignItems:'center',justifyContent:'center'},disabled:{opacity:.3},sendText:{fontSize:22,color:colors.ink,fontWeight:'800'}});
