import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,Alert,FlatList,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import { colors,editorial,aurora } from '../lib/theme';
import { AuroraBackdrop } from '../components/AuroraBackdrop';
import type { Conversation } from '../lib/types';

export default function Chats(){
 const {user}=useSession(); const [items,setItems]=useState<Conversation[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!user)return;const {data}=await supabase.from('conversation_members').select('conversation_id,archived,muted,last_read_at,conversations!inner(id,type,name,avatar_url,updated_at,last_message_at)').eq('user_id',user.id).eq('archived',false).order('joined_at',{ascending:false});if(!data){setLoading(false);return}const hydrated=await Promise.all(data.map(async(x:any)=>{const c={...x.conversations,muted:x.muted,last_read_at:x.last_read_at} as Conversation;const {data:count}=await supabase.rpc('get_unread_count',{p_conversation_id:c.id});return {...c,unread_count:Number(count??0)}}));setItems(hydrated);setLoading(false)},[user]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!user)return;const c=supabase.channel(`inbox:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'conversation_members',filter:`user_id=eq.${user.id}`},load).on('postgres_changes',{event:'*',schema:'public',table:'messages'},load).subscribe();return()=>{supabase.removeChannel(c)}},[user,load]);
 const filtered=useMemo(()=>items.filter(x=>(x.name??'Conversation').toLowerCase().includes(search.trim().toLowerCase())),[items,search]);
 const manage=useCallback((item:Conversation)=>{Alert.alert(item.name??'Conversation','Conversation actions',[{text:item.muted?'Unmute':'Mute',onPress:async()=>{const {error}=await supabase.rpc(item.muted?'unmute_conversation':'mute_conversation',{p_conversation_id:item.id});if(error)Alert.alert('Could not update',error.message);else load()}},{text:'Archive',onPress:async()=>{const {error}=await supabase.rpc('archive_conversation',{p_conversation_id:item.id});if(error)Alert.alert('Could not archive',error.message);else load()}},{text:'Cancel',style:'cancel'}])},[load]);
 return <View style={s.root}><AuroraBackdrop/><View style={s.header}><View><Text style={editorial.label}>PRIVATE / COMMUNITY</Text><Text style={editorial.title}>Messages</Text></View><View style={s.actions}><Pressable accessibilityRole="button" accessibilityLabel="Open profile" onPress={()=>router.push('/profile')}><Text style={s.action}>Profile</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Open settings" onPress={()=>router.push('/settings')}><Text style={s.action}>Settings</Text></Pressable><Pressable accessibilityRole="button" accessibilityLabel="Create a new group" onPress={()=>router.push('/new-group')} style={s.new}><LinearGradient colors={aurora.bluePurple} start={{x:0,y:1}} end={{x:1,y:0}} style={s.newGradient}><Text style={s.newText}>＋</Text></LinearGradient></Pressable></View></View><TextInput value={search} onChangeText={setSearch} accessibilityLabel="Search conversations" placeholder="Search conversations" placeholderTextColor={colors.muted} style={s.search}/>{loading?<ActivityIndicator color={colors.auroraSea} style={{marginTop:45}}/>:<FlatList data={filtered} keyExtractor={x=>x.id} contentContainerStyle={{paddingBottom:50}} ListEmptyComponent={<Text style={s.empty}>{search.trim()?'No matching conversations.':'No conversations yet. Start a private chat or create a group.'}</Text>} renderItem={({item})=><Pressable accessibilityRole="button" accessibilityLabel={`${item.name??'Conversation'}${(item.unread_count??0)>0?`, ${item.unread_count} unread`:''}`} style={s.row} onPress={async()=>{await supabase.rpc('mark_conversation_read',{p_conversation_id:item.id});router.push({pathname:'/chat/[id]',params:{id:item.id,name:item.name??'Conversation'}})}} onLongPress={()=>manage(item)}><View style={s.avatar}><LinearGradient colors={aurora.purpleGreen} style={s.avatarGradient}><Text style={s.avatarText}>{(item.name??'C').slice(0,1).toUpperCase()}</Text></LinearGradient></View><View style={{flex:1}}><View style={s.nameLine}><Text style={s.name}>{item.name??'Conversation'}</Text><Text style={s.date}>{item.last_message_at?new Date(item.last_message_at).toLocaleDateString([], {month:'short',day:'numeric'}):''}</Text></View><Text style={s.meta}>{item.type==='group'?'Group conversation':'Private conversation'}{(item as any).muted?' · muted':''}</Text></View>{(item.unread_count??0)>0&&<LinearGradient colors={aurora.greenSea} style={s.badge}><Text style={s.badgeText}>{(item.unread_count??0)>99?'99+':item.unread_count}</Text></LinearGradient>}<Text style={s.chev}>›</Text></Pressable>}/>}</View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink,paddingHorizontal:18},header:{paddingTop:60,paddingBottom:20,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},actions:{alignItems:'flex-end',gap:8},action:{color:colors.paperMuted,fontSize:10,fontWeight:'700'},new:{width:40,height:40,borderRadius:20,overflow:'hidden',marginTop:2},newGradient:{width:'100%',height:'100%',alignItems:'center',justifyContent:'center'},newText:{fontSize:25,color:colors.white,lineHeight:28},search:{height:50,borderRadius:12,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:16,marginBottom:10,fontSize:15},row:{minHeight:82,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',gap:13},avatar:{width:50,height:50,borderRadius:25,overflow:'hidden'},avatarGradient:{flex:1,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.white,fontSize:18,fontWeight:'800'},nameLine:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},name:{color:colors.paper,fontSize:16,fontWeight:'700'},date:{color:colors.muted,fontSize:10},meta:{color:colors.muted,fontSize:12,marginTop:5},badge:{minWidth:22,height:22,borderRadius:11,alignItems:'center',justifyContent:'center',paddingHorizontal:6},badgeText:{color:colors.ink,fontSize:10,fontWeight:'900'},chev:{fontSize:24,color:colors.muted},empty:{color:colors.muted,fontSize:14,lineHeight:21,paddingTop:35}});
