import { useCallback,useEffect,useMemo,useState } from 'react';
import { ActivityIndicator,FlatList,Pressable,StyleSheet,Text,TextInput,View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import { colors,editorial } from '../lib/theme';
import type { Conversation } from '../lib/types';

export default function Chats(){
 const {user}=useSession(); const [items,setItems]=useState<Conversation[]>([]); const [search,setSearch]=useState(''); const [loading,setLoading]=useState(true);
 const load=useCallback(async()=>{if(!user)return;const {data}=await supabase.from('conversation_members').select('conversation_id, conversations!inner(id,type,name,avatar_url,updated_at,last_message_at)').eq('user_id',user.id).order('joined_at',{ascending:false});if(data)setItems(data.map((x:any)=>x.conversations));setLoading(false)},[user]);
 useEffect(()=>{load()},[load]);
 useEffect(()=>{if(!user)return;const c=supabase.channel(`inbox:${user.id}`).on('postgres_changes',{event:'*',schema:'public',table:'conversation_members',filter:`user_id=eq.${user.id}`},load).on('postgres_changes',{event:'INSERT',schema:'public',table:'messages'},load).subscribe();return()=>{supabase.removeChannel(c)}},[user,load]);
 const filtered=useMemo(()=>items.filter(x=>(x.name??'Conversation').toLowerCase().includes(search.toLowerCase())),[items,search]);
 return <View style={s.root}><View style={s.header}><View><Text style={editorial.label}>PRIVATE / COMMUNITY</Text><Text style={editorial.title}>Messages</Text></View><View style={s.headerActions}><Pressable onPress={()=>router.push('/new-chat')} style={s.new}><Text style={s.newText}>＋</Text></Pressable><Pressable onPress={()=>supabase.auth.signOut()}><Text style={s.signout}>Exit</Text></Pressable></View></View><TextInput value={search} onChangeText={setSearch} placeholder="Search conversations" placeholderTextColor={colors.muted} style={s.search}/>{loading?<ActivityIndicator color={colors.paper} style={{marginTop:45}}/>:<FlatList data={filtered} keyExtractor={x=>x.id} contentContainerStyle={{paddingBottom:50}} ListEmptyComponent={<Text style={s.empty}>No conversations yet. Start one with the + button.</Text>} renderItem={({item})=><Pressable style={s.row} onPress={()=>router.push({pathname:'/chat/[id]',params:{id:item.id,name:item.name??'Conversation'}})}><View style={s.avatar}><Text style={s.avatarText}>{(item.name??'C').slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><View style={s.nameLine}><Text style={s.name}>{item.name??'Conversation'}</Text><Text style={s.date}>{item.last_message_at?new Date(item.last_message_at).toLocaleDateString([], {month:'short',day:'numeric'}):''}</Text></View><Text style={s.meta}>{item.type==='group'?'Group conversation':'Private conversation'}</Text></View><Text style={s.chev}>›</Text></Pressable>}/>}</View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink,paddingHorizontal:18},header:{paddingTop:60,paddingBottom:20,flexDirection:'row',justifyContent:'space-between',alignItems:'flex-end'},headerActions:{alignItems:'flex-end',gap:10},signout:{color:colors.muted,fontSize:12,fontWeight:'700'},new:{width:40,height:40,borderRadius:20,backgroundColor:colors.paper,alignItems:'center',justifyContent:'center'},newText:{fontSize:25,color:colors.ink,lineHeight:28},search:{height:50,borderRadius:12,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:16,marginBottom:10,fontSize:15},row:{minHeight:82,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',gap:13},avatar:{width:50,height:50,borderRadius:25,backgroundColor:colors.panel2,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},avatarText:{color:colors.paper,fontSize:18,fontWeight:'800'},nameLine:{flexDirection:'row',alignItems:'center',justifyContent:'space-between'},name:{color:colors.paper,fontSize:16,fontWeight:'700'},date:{color:colors.muted,fontSize:10},meta:{color:colors.muted,fontSize:12,marginTop:5},chev:{fontSize:24,color:colors.muted},empty:{color:colors.muted,fontSize:14,lineHeight:21,paddingTop:35}});
