import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import type { Profile } from '../lib/types';
import { colors, editorial } from '../lib/theme';

export default function NewChat() {
  const { user } = useSession();
  const [q,setQ]=useState(''); const [users,setUsers]=useState<Profile[]>([]); const [loading,setLoading]=useState(false); const [starting,setStarting]=useState<string|null>(null);
  useEffect(()=>{const t=setTimeout(async()=>{if(!q.trim()||!user){setUsers([]);return}setLoading(true);const term=q.trim().replace(/[%_,]/g,'');const {data}=await supabase.from('profiles').select('*').neq('id',user.id).or(`username.ilike.%${term}%,display_name.ilike.%${term}%`).limit(20);setUsers((data??[]) as Profile[]);setLoading(false)},250);return()=>clearTimeout(t)},[q,user]);
  async function start(other:Profile){if(!user||starting)return;setStarting(other.id);const {data,error}=await supabase.rpc('get_or_create_direct_conversation',{other_user_id:other.id});setStarting(null);if(!error&&data)router.replace({pathname:'/chat/[id]',params:{id:data,name:other.display_name??other.username??'Chat'}});}
  return <View style={s.root}><View style={s.header}><Pressable onPress={()=>router.back()} hitSlop={12}><Text style={s.back}>‹</Text></Pressable><View><Text style={editorial.label}>DIRECT</Text><Text style={s.title}>New conversation</Text></View></View><TextInput autoFocus value={q} onChangeText={setQ} placeholder="Search by name or username" placeholderTextColor={colors.muted} style={s.input}/>{loading?<ActivityIndicator color={colors.paper} style={{marginTop:30}}/>:<FlatList data={users} keyExtractor={x=>x.id} keyboardShouldPersistTaps="handled" contentContainerStyle={{paddingBottom:40}} ListEmptyComponent={q?<Text style={s.empty}>No members found.</Text>:<Text style={s.empty}>Search your community to start a private conversation.</Text>} renderItem={({item})=><Pressable style={s.row} onPress={()=>start(item)} disabled={!!starting}><View style={s.avatar}><Text style={s.avatarText}>{(item.display_name??item.username??'?').slice(0,1).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{item.display_name??item.username??'Member'}</Text><Text style={s.meta}>{item.username?`@${item.username}`:'Community member'}</Text></View>{starting===item.id?<ActivityIndicator color={colors.paper}/>:<Text style={s.arrow}>↗</Text>}</Pressable>}/>}</View>
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink,paddingHorizontal:18},header:{paddingTop:58,paddingBottom:22,flexDirection:'row',alignItems:'center',gap:12},back:{color:colors.paper,fontSize:38,fontWeight:'300'},title:{color:colors.paper,fontSize:24,fontWeight:'700',letterSpacing:-.6,marginTop:3},input:{height:52,borderRadius:12,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:16,marginBottom:10,fontSize:15},empty:{color:colors.muted,fontSize:14,lineHeight:21,paddingTop:35,paddingHorizontal:4},row:{minHeight:76,flexDirection:'row',alignItems:'center',gap:13,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line},avatar:{width:48,height:48,borderRadius:24,backgroundColor:colors.panel2,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},avatarText:{color:colors.paper,fontWeight:'800',fontSize:17},name:{color:colors.paper,fontWeight:'700',fontSize:16},meta:{color:colors.muted,fontSize:12,marginTop:4},arrow:{color:colors.paperMuted,fontSize:20}});
