import { useEffect, useState } from 'react';
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import type { Profile } from '../lib/types';
import { colors, editorial } from '../lib/theme';

export default function NewGroup(){
 const {user}=useSession(); const [name,setName]=useState(''); const [q,setQ]=useState(''); const [users,setUsers]=useState<Profile[]>([]); const [selected,setSelected]=useState<Set<string>>(new Set()); const [saving,setSaving]=useState(false);
 useEffect(()=>{const t=setTimeout(async()=>{if(!q.trim()||!user){setUsers([]);return}const term=q.trim().replace(/[%_,]/g,'');const {data}=await supabase.from('profiles').select('*').neq('id',user.id).or(`username.ilike.%${term}%,display_name.ilike.%${term}%`).limit(20);setUsers((data??[]) as Profile[])},220);return()=>clearTimeout(t)},[q,user]);
 function toggle(id:string){setSelected(prev=>{const n=new Set(prev);n.has(id)?n.delete(id):n.add(id);return n})}
 async function create(){if(!user||!name.trim()||selected.size===0||saving)return;setSaving(true);const {data,error}=await supabase.rpc('create_group_conversation',{p_name:name.trim(),p_member_ids:[...selected]});setSaving(false);if(!error&&data)router.replace({pathname:'/chat/[id]',params:{id:data,name:name.trim()}})}
 return <View style={s.root}><View style={s.header}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹</Text></Pressable><View><Text style={editorial.label}>COMMUNITY</Text><Text style={editorial.heading}>New group</Text></View></View><TextInput value={name} onChangeText={setName} placeholder="Group name" placeholderTextColor={colors.muted} style={s.input}/><TextInput value={q} onChangeText={setQ} placeholder="Add members" placeholderTextColor={colors.muted} style={s.input}/>{selected.size>0&&<Text style={s.selected}>{selected.size} member{selected.size===1?'':'s'} selected</Text>}<FlatList data={users} keyExtractor={x=>x.id} keyboardShouldPersistTaps="handled" renderItem={({item})=>{const on=selected.has(item.id);return <Pressable style={s.row} onPress={()=>toggle(item.id)}><View style={s.avatar}><Text style={s.avatarText}>{(item.display_name??item.username??'?')[0].toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{item.display_name??item.username??'Member'}</Text><Text style={s.meta}>{item.username?`@${item.username}`:'Community member'}</Text></View><View style={[s.checkbox,on&&s.checkboxOn]}>{on&&<Text style={s.tick}>✓</Text>}</View></Pressable>}} ListEmptyComponent={<Text style={s.empty}>Search for members to build your group.</Text>}/><Pressable disabled={!name.trim()||selected.size===0||saving} onPress={create} style={[s.create,(!name.trim()||selected.size===0||saving)&&s.disabled]}>{saving?<ActivityIndicator color={colors.ink}/>:<Text style={s.createText}>Create group · {selected.size}</Text>}</Pressable></View>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink,paddingHorizontal:18},header:{paddingTop:58,paddingBottom:22,flexDirection:'row',alignItems:'center',gap:12},back:{color:colors.paper,fontSize:38,fontWeight:'300'},input:{height:52,borderRadius:12,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:16,marginBottom:10,fontSize:15},selected:{color:colors.paperMuted,fontSize:12,marginVertical:8},row:{minHeight:72,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',gap:12},avatar:{width:44,height:44,borderRadius:22,backgroundColor:colors.panel2,alignItems:'center',justifyContent:'center',borderWidth:1,borderColor:colors.line},avatarText:{color:colors.paper,fontWeight:'800'},name:{color:colors.paper,fontSize:15,fontWeight:'700'},meta:{color:colors.muted,fontSize:11,marginTop:3},checkbox:{width:24,height:24,borderRadius:12,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center'},checkboxOn:{backgroundColor:colors.paper,borderColor:colors.paper},tick:{color:colors.ink,fontWeight:'900'},empty:{color:colors.muted,fontSize:14,lineHeight:21,paddingTop:25},create:{height:52,borderRadius:14,backgroundColor:colors.paper,alignItems:'center',justifyContent:'center',marginVertical:14},disabled:{opacity:.35},createText:{color:colors.ink,fontSize:15,fontWeight:'800'}});
