import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import { colors, editorial, aurora } from '../lib/theme';

export default function Profile(){const {user}=useSession();const [displayName,setDisplayName]=useState('');const [username,setUsername]=useState('');const [bio,setBio]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);useEffect(()=>{if(!user)return;supabase.from('profiles').select('*').eq('id',user.id).single().then(({data})=>{if(data){setDisplayName(data.display_name??'');setUsername(data.username??'');setBio(data.bio??'')}setLoading(false)})},[user]);async function save(){if(!user||saving)return;setSaving(true);setSaved(false);const {error}=await supabase.from('profiles').update({display_name:displayName.trim()||null,username:username.trim().toLowerCase()||null,bio:bio.trim()||null}).eq('id',user.id);setSaving(false);setSaved(!error)}if(loading)return <View style={s.root}><ActivityIndicator color={colors.auroraSea} style={{marginTop:80}}/></View>;return <ScrollView style={s.root} contentContainerStyle={s.content}><LinearGradient pointerEvents="none" colors={[colors.auroraBlue+'20',colors.auroraPurple+'12','transparent']} start={{x:1,y:0}} end={{x:.35,y:.6}} style={s.glow}/><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={editorial.label}>IDENTITY / PROFILE</Text><Text style={editorial.title}>Profile</Text><LinearGradient colors={aurora.purpleGreen} style={s.avatar}><View style={s.avatarInner}><Text style={s.avatarText}>{(displayName||username||'M')[0].toUpperCase()}</Text></View></LinearGradient><Text style={s.label}>DISPLAY NAME</Text><TextInput value={displayName} onChangeText={setDisplayName} placeholder="Your name" placeholderTextColor={colors.muted} style={s.input}/><Text style={s.label}>USERNAME</Text><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" placeholder="username" placeholderTextColor={colors.muted} style={s.input}/><Text style={s.label}>BIO</Text><TextInput value={bio} onChangeText={setBio} multiline maxLength={160} placeholder="A short introduction" placeholderTextColor={colors.muted} style={[s.input,s.bio]}/><Pressable onPress={save} disabled={saving} style={[s.save,saving&&s.disabled]}><LinearGradient colors={aurora.bluePurple} start={{x:0,y:0}} end={{x:1,y:0}} style={s.saveGradient}>{saving?<ActivityIndicator color={colors.white}/>:<Text style={s.saveText}>{saved?'Saved':'Save profile'}</Text>}</LinearGradient></Pressable></ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},content:{padding:18,paddingTop:58,paddingBottom:50},glow:{position:'absolute',top:-100,right:-170,width:430,height:430,borderRadius:215,opacity:.75},back:{color:colors.paperMuted,fontSize:14,marginBottom:28},avatar:{width:104,height:104,borderRadius:52,alignItems:'center',justifyContent:'center',marginVertical:28,overflow:'hidden'},avatarInner:{width:96,height:96,borderRadius:48,backgroundColor:colors.panel,alignItems:'center',justifyContent:'center'},avatarText:{color:colors.paper,fontSize:34,fontWeight:'800'},label:{color:colors.muted,fontSize:10,fontWeight:'800',letterSpacing:1.5,marginBottom:8,marginTop:14},input:{height:52,borderRadius:12,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:15,fontSize:15},bio:{height:100,textAlignVertical:'top',paddingTop:14},save:{height:52,borderRadius:14,overflow:'hidden',marginTop:24},saveGradient:{width:'100%',height:'100%',alignItems:'center',justifyContent:'center'},disabled:{opacity:.5},saveText:{color:colors.white,fontSize:15,fontWeight:'800'}});
