import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import { colors, editorial } from '../lib/theme';

export default function Profile(){const {user}=useSession();const [displayName,setDisplayName]=useState('');const [username,setUsername]=useState('');const [bio,setBio]=useState('');const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [saved,setSaved]=useState(false);useEffect(()=>{if(!user)return;supabase.from('profiles').select('*').eq('id',user.id).single().then(({data})=>{if(data){setDisplayName(data.display_name??'');setUsername(data.username??'');setBio(data.bio??'')}setLoading(false)})},[user]);async function save(){if(!user||saving)return;setSaving(true);setSaved(false);const {error}=await supabase.from('profiles').update({display_name:displayName.trim()||null,username:username.trim().toLowerCase()||null,bio:bio.trim()||null}).eq('id',user.id);setSaving(false);setSaved(!error)}if(loading)return <View style={s.root}><ActivityIndicator color={colors.paper} style={{marginTop:80}}/></View>;return <ScrollView style={s.root} contentContainerStyle={s.content}><Pressable onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={editorial.label}>IDENTITY</Text><Text style={editorial.title}>Profile</Text><View style={s.avatar}><Text style={s.avatarText}>{(displayName||username||'M')[0].toUpperCase()}</Text></View><Text style={s.label}>DISPLAY NAME</Text><TextInput value={displayName} onChangeText={setDisplayName} placeholder="Your name" placeholderTextColor={colors.muted} style={s.input}/><Text style={s.label}>USERNAME</Text><TextInput value={username} onChangeText={setUsername} autoCapitalize="none" placeholder="username" placeholderTextColor={colors.muted} style={s.input}/><Text style={s.label}>BIO</Text><TextInput value={bio} onChangeText={setBio} multiline maxLength={160} placeholder="A short introduction" placeholderTextColor={colors.muted} style={[s.input,s.bio]}/><Pressable onPress={save} disabled={saving} style={[s.save,saving&&s.disabled]}>{saving?<ActivityIndicator color={colors.ink}/>:<Text style={s.saveText}>{saved?'Saved':'Save profile'}</Text>}</Pressable></ScrollView>}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},content:{padding:18,paddingTop:58,paddingBottom:50},back:{color:colors.paperMuted,fontSize:14,marginBottom:28},avatar:{width:92,height:92,borderRadius:46,backgroundColor:colors.panel2,borderWidth:1,borderColor:colors.line,alignItems:'center',justifyContent:'center',marginVertical:28},avatarText:{color:colors.paper,fontSize:34,fontWeight:'800'},label:{color:colors.muted,fontSize:10,fontWeight:'800',letterSpacing:1.5,marginBottom:8,marginTop:14},input:{height:52,borderRadius:12,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,color:colors.paper,paddingHorizontal:15,fontSize:15},bio:{height:100,textAlignVertical:'top',paddingTop:14},save:{height:52,borderRadius:14,backgroundColor:colors.paper,alignItems:'center',justifyContent:'center',marginTop:24},disabled:{opacity:.5},saveText:{color:colors.ink,fontSize:15,fontWeight:'800'}});
