import { useEffect, useState } from 'react';
import { ActivityIndicator, Pressable, ScrollView, StyleSheet, Switch, Text, View } from 'react-native';
import { LinearGradient } from 'expo-linear-gradient';
import { router } from 'expo-router';
import { supabase } from '../lib/supabase';
import { useSession } from '../lib/session';
import { colors, editorial, aurora } from '../lib/theme';

export default function Settings() {
  const { user } = useSession();
  const [prefs,setPrefs]=useState({messages:true,mentions:true,group_messages:true,sound:true,badge:true});
  const [loading,setLoading]=useState(true); const [saving,setSaving]=useState<string|null>(null);
  useEffect(()=>{if(!user)return;supabase.from('notification_preferences').select('*').eq('user_id',user.id).single().then(({data})=>{if(data)setPrefs({messages:data.messages,mentions:data.mentions,group_messages:data.group_messages,sound:data.sound,badge:data.badge});setLoading(false)})},[user]);
  async function toggle(key:keyof typeof prefs){if(!user||saving)return;const next={...prefs,[key]:!prefs[key]};setPrefs(next);setSaving(key);const {error}=await supabase.from('notification_preferences').upsert({user_id:user.id,...next});if(error)setPrefs(prefs);setSaving(null)}
  if(loading)return <View style={s.root}><ActivityIndicator color={colors.auroraSea} style={{marginTop:80}}/></View>;
  return <ScrollView style={s.root} contentContainerStyle={s.content}><Pressable accessibilityRole="button" accessibilityLabel="Go back" onPress={()=>router.back()}><Text style={s.back}>‹ Back</Text></Pressable><Text style={editorial.label}>ACCOUNT / PREFERENCES</Text><Text style={editorial.title}>Settings</Text><View style={s.hero}><LinearGradient colors={aurora.purpleGreen} start={{x:0,y:0}} end={{x:1,y:1}} style={s.heroGlow}/><Text style={s.heroLabel}>AURORA SYSTEM</Text><Text style={s.heroText}>Quiet by default. Precise when it matters.</Text></View><View style={s.section}><Text style={s.sectionTitle}>Notifications</Text>{([['messages','Direct messages'],['mentions','Mentions'],['group_messages','Group messages'],['sound','Sound'],['badge','App badge']] as const).map(([key,label])=><View style={s.row} key={key}><View><Text style={s.rowText}>{label}</Text><Text style={s.rowMeta}>{key==='messages'?'Conversation alerts':key==='mentions'?'@mentions and replies':key==='group_messages'?'Activity in groups':key==='sound'?'Notification audio':'Unread count on app icon'}</Text></View><Switch value={prefs[key]} disabled={saving!==null} onValueChange={()=>toggle(key)} trackColor={{false:colors.line,true:colors.auroraPurple}} thumbColor={prefs[key]?colors.auroraSea:colors.muted}/></View>)}</View><View style={s.section}><Text style={s.sectionTitle}>Session</Text><Pressable accessibilityRole="button" style={s.danger} onPress={()=>supabase.auth.signOut()}><Text style={s.dangerText}>Sign out</Text></Pressable></View></ScrollView>;
}
const s=StyleSheet.create({root:{flex:1,backgroundColor:colors.ink},content:{padding:18,paddingTop:58,paddingBottom:50},back:{color:colors.paperMuted,fontSize:14,marginBottom:28},hero:{height:120,borderRadius:18,backgroundColor:colors.panel,borderWidth:1,borderColor:colors.line,overflow:'hidden',padding:18,justifyContent:'flex-end',marginTop:28},heroGlow:{position:'absolute',right:-70,top:-70,width:220,height:220,borderRadius:110,opacity:.32},heroLabel:{color:colors.auroraSea,fontSize:9,fontWeight:'900',letterSpacing:1.8},heroText:{color:colors.paper,fontSize:17,fontWeight:'700',lineHeight:22,maxWidth:270,marginTop:5},section:{marginTop:38,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:colors.line},sectionTitle:{color:colors.muted,fontSize:10,fontWeight:'800',letterSpacing:1.6,textTransform:'uppercase',marginVertical:14},row:{minHeight:68,borderBottomWidth:StyleSheet.hairlineWidth,borderBottomColor:colors.line,flexDirection:'row',alignItems:'center',justifyContent:'space-between',gap:12},rowText:{color:colors.paper,fontSize:15,fontWeight:'600'},rowMeta:{color:colors.muted,fontSize:10,marginTop:3},danger:{paddingVertical:16},dangerText:{color:colors.danger,fontSize:15,fontWeight:'700'}});